Fix coefficient vector with restriction
Sammers21/math_stat_python pull request #30
Opened 2017-06-05 20:07 UTC by Flatout73

Я еще тот гавнокодер, так что проверьте на всякий :)

2017-06-05 22:37 UTC, Sammers21 commented
@Flatout73 ты случайно какой-то бинарник закоммитил

2017-06-05 22:38 UTC, Sammers21 commented
Я так понимаю это фикс к  #27

2017-06-05 22:39 UTC, Sammers21 commented
Вот какой то странный бинарник  __pycache__/lib.cpython-36.pyc

2017-06-05 23:59 UTC, Flatout73 commented
@Sammers21, удалил бинарник

2017-06-06 12:25 UTC, Sammers21 requested changes

2017-06-06 12:25 UTC, Sammers21 commented on problem4.py
> -    x_step1 = numpy.dot(x.T, x) + ar
кажись тут ты зря сделал. Тут вообще матрица ar прибавляется это для риджа

2017-06-06 12:37 UTC, Flatout73 commented on problem4.py
> -    x_step1 = numpy.dot(x.T, x) + ar
ну это в целом никак не влияет на решение с риджом, а доп условие я сделал чтобы не было проблем с разной размерностью при прибавлении ar, так как там где нужна restricted ridge же не нужна

2017-06-06 12:52 UTC, merged